Docs: Initial docs
trilitech/jstz pull request #31
Opened 2023-10-02 10:27 UTC by sam-finch-tezos

# Context
Now that JsTz is coming along people might want to use it. We need to begin documenting what we're creating.
# Description
This PR creates some initial documentation and lays out some of the structure going forwards. 
# Manually testing the PR
[https://www.wikihow.com/Teach-Yourself-to-Read](www.wikihow.com/Teach-Yourself-to-Read)

2023-10-04 13:54 UTC, asutosh-mourya requested changes
Left a few comments, I think written jokes could be easily misinterpreted by people who don't know the writer so it would be better to remove those.

2023-10-04 13:54 UTC, asutosh-mourya commented on docs/getting-started/installation/index.md
> +If anything doesn't work we'd love to hear from you. (Actually we'll hate it. We're only human and we're like fixing people's builds as much as anybody else, but we grudgingly accept it will make the
while really funny,  I think such jokes could be easily misinterpreted by people who don't know the writer.

2023-10-04 13:54 UTC, asutosh-mourya commented on docs/getting-started/installation/index.md
> +I think the view from core is that we don't actually need this step, just get the octez binaries from somewhere.
Can we please change this?

2023-10-04 13:54 UTC, asutosh-mourya commented on docs/getting-started/installation/index.md
> +If anything went wrong whe  the it's probably our fault not yours.
Please remove this :)

2023-10-05 11:46 UTC, alanmarkoTrilitech approved these changes
LGTM!

2023-10-05 11:46 UTC, alanmarkoTrilitech commented on docs/getting-started/my_first_smart_function/index.md
> +JsTz smart functions are modeled on http servers. These designed to be more familiar to most developers and to integrate better with the off chain part of your dApp.
These designed -> These are designed

2023-10-10 12:19 UTC, johnyob commented
Closing in favour of #35

2023-10-10 12:19 UTC, closed without merging