Ryutamago/cli trace
trilitech/jstz pull request #404
Opened 2024-02-19 15:57 UTC by ryutamago

# Context

# Description

# Manually testing the PR

2024-02-21 17:14 UTC, johnyob requested changes
Overall the code looks good (needs rebasing though). 

Appears to be a race condition between the spinner and the trace thread which causes a panic on my machine:
<img width="1180" alt="image" src="https://github.com/trilitech/jstz/assets/9090566/2f5b3131-e779-43d9-8c15-379ad7dac72b">

2024-02-23 13:24 UTC, johnyob requested changes
Is it possible to remove that strange newline:
<img width="1132" alt="image" src="https://github.com/trilitech/jstz/assets/9090566/ea8db2f3-ec6e-475c-a073-dd39df1063bd">

2024-02-23 15:59 UTC, alanmarkoTrilitech approved these changes
LGTM! great trace spinner.

2024-02-27 14:30 UTC, johnyob approved these changes

2024-02-27 14:30 UTC, merged