Docs: URL
trilitech/jstz pull request #53
Opened 2023-10-13 15:11 UTC by sam-finch-tezos

# Context

**Related Tasks**: [API doc: URL](https://app.asana.com/0/1205170694555856/1205457666696789/f)

# Description

This PR an API reference and quick start for the `URL` runtime API

# Manually testing the PR
```sh
npm run docs:dev
```

2023-10-16 10:25 UTC, johnyob commented on docs/api/url.md
> +An API for working with HTTP URLs.
Please link mdn + spec pages

2023-10-16 10:25 UTC, johnyob commented on docs/api/url.md
> +```
We should take the opportunity (here initially) to explain the `tezos://` scheme

2023-10-16 10:25 UTC, johnyob commented on docs/api/url.md
> +let url = new URL('tezos://domain/);
`domain` -> `host`/`address` (we don't support DNS yet)

2023-10-16 10:25 UTC, johnyob commented on docs/api/url.md
> +url.hostname = Ledger.selfAddress();
`selfAddress` is a property, not a function:

```suggestion
url.hostname = Ledger.selfAddress;
```

2023-10-16 10:25 UTC, johnyob commented on docs/api/url.md
> +```
We should try to avoid `foo` & `bar` in our documentation and stick to real world examples

2023-10-16 10:25 UTC, johnyob commented on docs/api/url.md
> +Search parameters may be read or edited through the [`URLSearchParams`](./url_search_params.md) API.
Makes `.searchParams` explicit in the description associated w/ the example below:

```suggestion
The [`URLSearchParams`](./url_search_params.md) API may be used to build and manipulate search parameters. To get the search parameters from the URL, you may use the `.searchParams` instance property.
```

2023-10-18 11:11 UTC, johnyob requested changes

2023-10-18 11:11 UTC, johnyob commented on docs/api/url.md
> +An API for working with [HTTP](https://developer.mozilla.org/en-US/docs/Web/HTTP) [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL)s.
This should be phrased as `jstz` implementing the URL spec.
Additionally URLs aren't defined by the HTTP specification.

2023-10-18 11:11 UTC, johnyob commented on docs/api/url.md
> +We can construct a url in two ways, either as an absolute url or a relative url.
url -> URL

2023-10-18 11:11 UTC, johnyob commented on docs/api/url.md
> +Jstz smart functions each have their own unique address which is generated by jstz when the contract is deployed.
Jstz -> `jstz` (current style in this docs)
jstz -> `jstz`

2023-10-18 11:11 UTC, johnyob commented on docs/api/url.md
> +These are loosely analagous to http addresses. Jszt has its own URI scheme `tezos` to refer to contracts.
IP addresses, not HTTP addresses
URI -> URL

2023-10-18 11:11 UTC, johnyob commented on docs/api/url.md
> +The constructor will raise and exception if the arguments cannot be parsed into a valid url.
Maybe mention that the exception is a `TypeError`

2023-10-18 11:11 UTC, johnyob commented on docs/api/url.md
> +Jstz smart functions each have their own unique address which is generated by jstz when the contract is deployed.
Apply renaming elsewhere in this doc

2023-10-18 11:11 UTC, johnyob commented on docs/api/url.md
> +We can construct a url in two ways, either as an absolute url or a relative url.
Apply renaming elsewhere in this doc

2023-10-18 11:11 UTC, johnyob commented on docs/api/url.md
> +let url = new URL('tezos://domain/); // not a valid jstz hostname, we'll have to change it
Missing a `'` at the end

2023-10-18 11:11 UTC, johnyob commented on docs/api/url.md
> +url.hash = "my_fragment"
Provide real-word path / hash

2023-10-24 10:18 UTC, asutosh-mourya reviewed
the document is pretty well reviewed already please address the comments, Nothing else to add from my side.

2023-10-25 14:22 UTC, johnyob commented
@sam-finch-tezos please see [062e788](https://github.com/trilitech/jstz/pull/53/commits/062e788d1e0077326838014c597d7e57988c004c) for the review commit addressing all comments above

2023-10-27 14:03 UTC, johnyob approved these changes
LGTM

2023-10-27 14:04 UTC, merged